### ISSUE TITLE
Date and Time pickers for inputs

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/native#10]
_From @rickardinho on December 4, 2016 19:52_

I have currently left this as Text input for simplicity for now, but will have a look at DatePicker solutions.  React native has seperate pickers for iOS and Android, so we might need to have separate components for each.  Leave this for Dave to look at.

_Copied from original issue: DRDD2016/sparkn2#7_

**Comment by minaorangina** [comment]
_From @heron2014 on December 14, 2016 17:15_

Hi @rickardinho

Have you done any research on this yet? If yes, please put the link to the module. Thanks

**Comment by minaorangina** [comment]
_From @heron2014 on December 14, 2016 17:27_

Hi again @rickardinho 

Actually there is a way to render specific DatePicker component depending on which platform is being used. React native can detect which operating system is being used. 

Since it needs to be hooked up with redux we think we will implement that.

**Comment by minaorangina** [comment]
_From @rickardinho on December 15, 2016 12:55_

That was the conclusion I was coming to. There doesn't seem to be a cross-platform solution.  Happy for you to go ahead with what you think works for now.

**Comment by heron2014** [comment]
Resolved by #72
