### ISSUE TITLE
Feed is loading slowly

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/native#11]
_From @rickardinho on December 4, 2016 20:16_

I think this is because I should replace the current ScrollView with a ListView.  I will look at this once the authentication layer is built.  Will only be an issue when the user has lots of events(like me). If database is flushed it shouldn't be too bad.

_Copied from original issue: DRDD2016/sparkn2#8_

**Comment by heron2014** [comment]
This is no longer relevant
