### ISSUE TITLE
Connecting socket.io to React Native 

### ISSUE THREAD

**Issue by heron2014** [DRDD2016/native#110]
Collections of steps and references how to deal with real time stuff, using socket.io.

**Comment by minaorangina** [comment]
### Client side
* **Connect to our websocket server, under the `/feed` namespace** (like an endpoint)
All socket.io namespaces are separate from each other.  Namespaces are optional, but useful if you want to have different sockets for different things that don't overlap

* **Subscribe to the following custom events: 
  `connected`** - emitted by server when it receives connection from client 
  **`feed: ${token}`** - emitted by server when ready to push feed data to client
  **`failure`** - emitted by server when something went wrong
* **Wait to receive a `connected` event from the server**
`connected` is a custom event that we've made.

#### On `connected`
* emit `INIT_FEED` to server.  Send the token
* dispatch `getFeedRequest()`
#### On `feed: ${token}`
* dispatch `getFeedSuccess(feedData)`
#### On `failure`
* dispatch `getFeedFailure(error)


#### Core concept
* Each user will be subscribed to a custom event, `feed: ${token}`
* Each `token` is unique, and so each event will be personal to that user
* The token will be used on the server side to add feed items for the right user(s) in the database
* The token will also be used to deliver feed items to the correct socket client
