### ISSUE TITLE
EventDetailsHeader now included in each component

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/native#12]
_From @rickardinho on December 4, 2016 20:19_

Create event sub-header now included within each create-event component, as nested routes not allowed in react-native-router-flux (to my knowledge).  So now it is imported into each component and any redux logic in the create-event container has had to be moved into individual component containers.

_Copied from original issue: DRDD2016/sparkn2#9_

**Comment by heron2014** [comment]
Replaced by navigationBar from ex-navigation. Resolved by #71
