### ISSUE TITLE
Duplicate feed items

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/native#179]
Feed items will repeat themselves.

Sometimes this is just due to the simulator hot reloading.  But on the server side, `UPDATE_FEED` will be triggered multiple times on each refresh (once, twice, 3, 4, 5 etc)

Current fix:
- the server `INIT_FEED` publishes a pubsub event called `HYDRATE_FEED`.  This means initialising the feed and adding new feed items are conceptually separated out.
- on the client, on `hydratefeed${user_id}`, doing the following check:
```js
// src/js/socket-router.js
socket.on(`hydrateFeed:${user_id}`, (data) => {
  const existingFeed = store.getState().feed.data;
  if (existingFeed.length === 0) { // only add to feed if it's empty (avoid duplicates)
    store.dispatch(getFeedSuccess(data));
  }
});
```

The feed is hydrated only if it hasn't been hydrated already.

**Comment by heron2014** [comment]
Currently this big has been resolved by #180
