### ISSUE TITLE
Hot reloading

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/native#19]
_From @minaorangina on December 5, 2016 15:11_

Does React Native support it?

_Copied from original issue: DRDD2016/sparkn2#17_

**Comment by minaorangina** [comment]
_From @heron2014 on December 10, 2016 10:30_

Yes it does. Reference https://facebook.github.io/react-native/blog/2016/03/24/introducing-hot-reloading.html

**Comment by heron2014** [comment]
Hot reloading works when we have migrated code to the new repo. I am guessing we really messed up the previous repo! 

I am closing this issue for now.
