### ISSUE TITLE
Forgot password not working

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#193]
If I click forgot password and enter the email address i signed up with, I get the error message "Something went wrong" after clicking Submit.
![img_5321](https://cloud.githubusercontent.com/assets/17908724/23437263/5931172c-fe05-11e6-960a-a1e5e91901b5.PNG)

**Comment by minaorangina** [comment]
@rickardinho Should be fixed now.  If so, please close.

**Comment by rickardinho** [comment]
So it now works for one account.
For the other email account, the emails were going to my spam folder ( i guess we can't do much about that other than highlight to check spam folder in the messaging), but then when i click the link I get this page - see screenshot.

![screenshot_20170301-231113](https://cloud.githubusercontent.com/assets/17908724/23485811/03f79dbe-fed5-11e6-8269-a349d76ffe62.png)

**Comment by heron2014** [comment]
@rickardinho is this issue appears on Iphone?

**Comment by rickardinho** [comment]
oops, this one was Android, sorry.  I'll see if i can recreate it on iPhone (I'm thinking it could be related to Heroku plan downtime?)
