### ISSUE TITLE
Keyboard hiding input fields and not allowing scrolling.

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#194]
Login screen - Scroll not allowing me to see password when typing in input text box, keyboard hides the boxes at bottom of screen, either needs to scroll above keyboard so can see box as I'm typing.
This is happening on all screens with inputs that show the keyboard. (eg. What, where, when too).

**Comment by rickardinho** [comment]
![img_5296](https://cloud.githubusercontent.com/assets/17908724/23438909/fbec33ce-fe0b-11e6-848c-c5fe2d166295.PNG)
in this example Confirm password is hidden from view.  User has to press Return to see the login button, but they should be able to see the Login button as soon as the password is typed in and of the minimum length.

**Comment by rickardinho** [comment]
This article was recommended in my Medium feed... perhaps its helpful?
“How to make your React Native app respond gracefully when the keyboard pops up” @spencer_carli 
https://medium.freecodecamp.com/how-to-make-your-react-native-app-respond-gracefully-when-the-keyboard-pops-up-7442c1535580

**Comment by heron2014** [comment]
@rickardinho this should be fixed now.

**Comment by rickardinho** [comment]
closing - fixed.
