### ISSUE TITLE
Google Places default to UK places as priority?

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#198]
Google places showing US cities first… can we default based on UK as the home location for now (can we have home country as a variable somewhere in a file within the code)?

**Comment by heron2014** [comment]
@rickardinho This is more like a enhancement than a bug. I found the quick solution so once the PR #225 is merged we can test it.

**Comment by heron2014** [comment]
@rickardinho this should work now.

**Comment by rickardinho** [comment]
closing.
