### ISSUE TITLE
Errors after creating an event (Feed blank, etc)

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#199]
After inviting friends in WhatsApp, if I click back to Spark via the back button at the top of the screen, I get a screen that shows TBC for What and Where and today’s date, rather than the details I just polled on - see screenshot. 

![img_5322](https://cloud.githubusercontent.com/assets/17908724/23437737/21647242-fe07-11e6-86cf-dd23dbcca8c5.PNG)

 If I then click ‘Feed’ the feed is blank…. not even a message saying no events. see screenshot. 
![img_5323](https://cloud.githubusercontent.com/assets/17908724/23437750/2f76c132-fe07-11e6-808e-7bf8004e053a.PNG)

 I have to kill the app and reload for the feed to be populated… 3rd screenshot.  Logout isn't enough, I have to kill the app for the feed to show.  The feed shows okay if I click Calendar before clicking on the feed immediately after the invite screen.
![img_5324](https://cloud.githubusercontent.com/assets/17908724/23437783/4cd70214-fe07-11e6-8905-d258acf90412.PNG)

Feed also shows blank if I click an event (in the feed) to look at the event details (poll).  When I return to the feed it is blank.  If I also try and click on Code at this point, the heading of the screen is Feed with a blank page (but the Code button on the tabbar is highlighted blue).

**Comment by heron2014** [comment]
@rickardinho these two issues should be working now.

**Comment by rickardinho** [comment]
fixed
