### ISSUE TITLE
Unrecognised Places errors

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#200]
If I enter a non-google place (e.g. ‘Home’), after I click Return on the keyboard, the suggested names do not disappear and I cannot add other options or click Next - see screenshot.
![img_5325](https://cloud.githubusercontent.com/assets/17908724/23437992/fb683636-fe07-11e6-9e88-9e52d772670a.PNG)

Even a real address that cannot be found does the same (this is my address) - see screenshot.

![img_5326](https://cloud.githubusercontent.com/assets/17908724/23437997/00e15c96-fe08-11e6-8c06-3ff557d8ca02.PNG)

**Comment by heron2014** [comment]
@rickardinho This should be fixed now. When you click away from the input the buttons re-appear.
The custom value is now passed to the state.

**Comment by rickardinho** [comment]
Fixed but created another issue #240
