### ISSUE TITLE
When issues

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#201]
Can’t leave time/date blank if I want to leave it as TBC as I could in the web app.

Also can’t remove date option (no cross to click) from when - see screenshot.

![img_5327](https://cloud.githubusercontent.com/assets/17908724/23438267/207ab1d2-fe09-11e6-9d76-629d428cdcd4.PNG)

**Comment by heron2014** [comment]
First part is done in #253

**Comment by minaorangina** [comment]
@rickardinho see https://github.com/DRDD2016/native/issues/242#issuecomment-285738699
