### ISSUE TITLE
Feed errors

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#203]
After joining a poll, using Code, I click on Calendar… but the feed shows.  Also the event i previously created in the feed is highlighted red (requiring action)… but not sure why as I have actioned(created it).
![img_5329](https://cloud.githubusercontent.com/assets/17908724/23438507/10567948-fe0a-11e6-83c1-b23e18d7decf.PNG)

Another weird issue occurred at 22:13 (if you can check logs)… I go back to the feed and click on the event and it flashes red (see screenshot).. but doesn’t open.  
![img_5328](https://cloud.githubusercontent.com/assets/17908724/23438524/2953f33a-fe0a-11e6-80e5-a46031e2577f.PNG)

Then i get a message saying the event has been cancelled (like in issue #190)
… but i didn’t cancel it.  I go back to the feed and the event is there again.

**Comment by heron2014** [comment]
@rickardinho this should be fixed now. Please test.

**Comment by rickardinho** [comment]
fixed
