### ISSUE TITLE
Unstable behaviour - various issues

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#206]
Raising this as one issue as not seen these errors at other times.
At around 23:35, this sequence of events showed unstable behaviour:

When responding to poll, ‘Thanks for voting’ is displayed even before i have voted, see screenshot.
![img_5330](https://cloud.githubusercontent.com/assets/17908724/23439660/a2d13d58-fe0f-11e6-89ec-a6e0ef38a1af.PNG)

After responding, the feed now shows the event i responded two (second one on the feed) and says I’ve created an event of the same name (first one in the feed), which i didn’t) - see screenshot:

![img_5331](https://cloud.githubusercontent.com/assets/17908724/23439703/d4960e04-fe0f-11e6-85b4-4dc9261960f5.PNG)

My poll also shows under ‘received’, which it shouldn’t if i created it (but then again, I didn’t):
![img_5333](https://cloud.githubusercontent.com/assets/17908724/23439712/eccedf64-fe0f-11e6-928c-05e16ccef88f.PNG)

When clicking on Code, I get “JSON Parse errorL Unrecognised token ‘<‘“:
![img_5332](https://cloud.githubusercontent.com/assets/17908724/23439715/f68a2a22-fe0f-11e6-98ae-4f31d3010550.PNG)

Then I try and create a new event, and clicking Invite Friends does nothing… doesn’t go to WhatsApp as expected but stays on this screen…
![img_5334](https://cloud.githubusercontent.com/assets/17908724/23439728/06b5cd98-fe10-11e6-84c5-0cbc7376cd75.PNG)

**Comment by heron2014** [comment]
@rickardinho this issue is done partially. Please test the 'thanks for voting'. 

With the JSON.parse error what exactly were your steps to reproduce this error? 

Thanks

**Comment by rickardinho** [comment]
I haven't experienced any of these errors since, so closing this issue.  I'll re-raise if any further occurances.
