### ISSUE TITLE
Editing event unstable at remembering data

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#209]
If the user edits the event, the “Where” options are showing as blank.  
![img_5305](https://cloud.githubusercontent.com/assets/17908724/23440477/0bda2e46-fe14-11e6-9f7c-c30452f43a5a.PNG)

But if I click next (leave them as blank) then go to the end details screen one option is there, with two TBCs:
![img_5304](https://cloud.githubusercontent.com/assets/17908724/23440481/11987356-fe14-11e6-8cbc-40e6bc525768.PNG)

We've tried a few times the same sequence of events and it seems to randomly keep or remove the Where details (sometimes it shows them in the Where screen and then at the end all options are TBC.

**Comment by heron2014** [comment]
@rickardinho it should work now.

**Comment by rickardinho** [comment]
closing as appears fixed.
