### ISSUE TITLE
App freeze in between scenes

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#210]
App froze when between two screens (frozen as in screenshot).
This happened when clicking on event in feed.

Some screens also show the word "Sorry..." at the top when confirming a Poll.

![bug](https://cloud.githubusercontent.com/assets/17908724/23440671/53f3353c-fe15-11e6-99a5-da0e77c184ba.PNG)

**Comment by heron2014** [comment]
@rickardinho this should be fixed now. Please test.

**Comment by rickardinho** [comment]
Freeze not recurred, so closing.  But "Sorry" title text raised seperately as #237
