### ISSUE TITLE
Calendar showing incorrect events

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#211]
Calendar shows events that I didn't create or join (Test).  These were created by another user on the same phone:
![img_5340](https://cloud.githubusercontent.com/assets/17908724/23440764/1bc8b9ce-fe16-11e6-91d9-7b28cb6434e9.PNG)
If I then click on Feed, it says I created these events, but I didn't create them (Flora did):
![img_5341](https://cloud.githubusercontent.com/assets/17908724/23440772/323919a6-fe16-11e6-8dfa-c137af5a2294.PNG)

**Comment by heron2014** [comment]
@rickardinho this should be fixed now.

**Comment by rickardinho** [comment]
no recurrance of this so I'm closing.  Will reopen if it reappears.
