### ISSUE TITLE
No way to invite more friends to an existing event

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#212]
How can we invite more friends to an existing event.  Shouldn't there be a button in the screen below saying "Invite More Friends"?
![img_5336](https://cloud.githubusercontent.com/assets/17908724/23440826/81718d14-fe16-11e6-97b1-6e6ba77479d9.PNG)

**Comment by minaorangina** [comment]
@rickardinho Yes there should, we'll add it.

**Comment by heron2014** [comment]
@rickardinho the button should be there now.

**Comment by rickardinho** [comment]
Not able to test this yet as polls / events are still disappearing from the Feed before i can Confirm them.

**Comment by rickardinho** [comment]
fixed.  closing issue.
