### ISSUE TITLE
Red Screens of Death

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#213]
These screens popped up early today before I pulled the latest version.  Haven't seen them since.
![img_5314](https://cloud.githubusercontent.com/assets/17908724/23440890/ed92f06e-fe16-11e6-95fc-b5dde3a9e80a.PNG)

![img_5315](https://cloud.githubusercontent.com/assets/17908724/23440894/f28933e4-fe16-11e6-839a-c9f64956c078.PNG)

![img_5316](https://cloud.githubusercontent.com/assets/17908724/23440899/f7d9b044-fe16-11e6-911a-391156d3297a.PNG)

![img_5317](https://cloud.githubusercontent.com/assets/17908724/23440905/fd75936a-fe16-11e6-9ec5-fe0e4aa70745.PNG)

**Comment by heron2014** [comment]
@rickardinho should be fixed now. Please close once tested.

**Comment by rickardinho** [comment]
closing and will reopen if any further issues like this
