### ISSUE TITLE
Confirm event details issues

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#219]
When confirming event details after poll responses, I can select options and click Confirm Event Details.  The screem then remains on screen (should go back to the feed after showing event finalised message). I can then make different selections and confirm again, which is not supposed to be allowed if it goes back to the feed.

Then if I click Calendar and then Feed it shows the Confirm event screen again (instead of the Feed), and the Feed button is highlighted on the tab bar.

**Comment by heron2014** [comment]
@rickardinho Relates to this comment https://github.com/DRDD2016/native/issues/251#issuecomment-285054520
