### ISSUE TITLE
No votes are displayed on poll responses

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#223]
Host View doesn't show tally of responses (numbers or bars).

**Comment by minaorangina** [comment]
@rickardinho We've made some changes.  Have a try and let us know if it's fixed.

**Comment by rickardinho** [comment]
Still can't see any votes in the Host view (i voted for Swimming, Sailing, East London and 5 Aug as a an Invitee) - pulled from Github at 6.30pm this evening Mar 2

![img_5433](https://cloud.githubusercontent.com/assets/17908724/23526533/47a17c78-ff8a-11e6-9469-3474be06f8c5.PNG)

**Comment by rickardinho** [comment]
Still no votes showing I'm afraid.  I tried switching to Landscape in case they were off screen , but nothing.  There should be 1 vote for skiing, and 1 for snowboarding.
![img_5455](https://cloud.githubusercontent.com/assets/17908724/23571362/c187e352-0060-11e7-9a22-4c3983377823.PNG)
![img_5456](https://cloud.githubusercontent.com/assets/17908724/23571366/c4b35c0a-0060-11e7-8927-2f685fadc604.PNG)

**Comment by rickardinho** [comment]
removed "please test" so its clear that its not fixed.

**Comment by minaorangina** [comment]
@rickardinho Just pushed a fix for this.  Take a look and let us know if it's fixed

**Comment by rickardinho** [comment]
fixed
