### ISSUE TITLE
Invite friends button not working

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#224]
I created an event with just one option for what, where, when... but when I click Invite friends, nothing happens.

**Comment by heron2014** [comment]
@rickardinho just to make sure, could you please clarify that you were testing on Iphone?

**Comment by rickardinho** [comment]
yes, iphone 5s.  I haven't done any testing on Android... other than just to get the app to launch (which is why i raised the pull request last night).  I don't plan to any further testing on Android until the iPhone version is 100% stable.

**Comment by rickardinho** [comment]
just a thought, could this be related to the Heroku plan, it mentions 4 hours of downtime per month, could we be unlucky and this coincided with our testing?  I seemed to get a lot of these issues after about 11pm, so wondering if they shut it down late at night?

**Comment by minaorangina** [comment]
@rickardinho you may well be right.  I need to keep the server ownership until we're done, but if you're happy I can upgrade the server to the $7/month plan and get a $9 database, like before.  I think payment is taken after the month is up, but if not I'll just invoice you the cost?

**Comment by rickardinho** [comment]
Happy at these rates. When I tried to do it it said $50 per month, but maybe I was looking at the wrong section.

**Comment by minaorangina** [comment]
@rickardinho Ok.  It will be much easier to get a new database than upgrade the current one.  I'll let you know the new environment variables and you'll have to sign up etc again.

**Comment by rickardinho** [comment]
fixed closed
