### ISSUE TITLE
change of profile photo not saving

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#226]
I changed profile photo and the new photo was displaying.  I clicked Save and then went to different screens.  Logged out and then came back to Profile and the old photo is still displaying.

**Comment by heron2014** [comment]
@rickardinho I have just followed your steps on my iphone and I couldn't reproduce this bug. Could you please clarify that you were testing in Iphone?

**Comment by rickardinho** [comment]
yes.  iphone 5s.  Have you tried logging in with multiple email addresses... maybe its having 2 accounts on one phone that is causing the issue?  Just to clarify, I have been pulling down from Github, then deleting the old install of Spark on the iPhone, before building and running the new version.  Do i need to do any other data cleaning off the iPhone before running the new version (could it be old data thats causing the issue?).

**Comment by heron2014** [comment]
@rickardinho this issue should be fixed now. Please test.

**Comment by rickardinho** [comment]
fixed
