### ISSUE TITLE
Issues when Entering Code

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#230]
If a user enters a code to join an event which is incorrect, there is no error message.  Also, if its slow to load from the server (for a correct code), the user doesn't know whats happening and they might give up.  We should add a spinner while its checking if its a correct code and then an error message if the code is unsuccessful.

Also, what happens if a user enters the same code twice.  They might forget they'd already replied and it looks like they could go through and vote again.  Currently, are the votes counted twice? Or does it "redo" the vote.  Eg. if I vote for Pizza the first time, and Burgers the second time, does it record one vote against Pizza and one vote for Burgers, or does it just show one vote for Burgers.

If I go back to an event a second time and I've already voted it should show me my previous selections (so I know that I've already voted once).

**Comment by heron2014** [comment]
First part is done - Spinner is now showing on fetching. 

Second part - show previous votes (to be complete)

**Comment by minaorangina** [comment]
@rickardinho yes, if someone votes again their new vote is counted and the old one deleted, so considered a re-vote.  The total number of votes (for the host) will reflect this.

An invitee's old votes should be visible now, take a look.

**Comment by rickardinho** [comment]
Still not working when I've tested this.   See screenshots

1st vote:
![img_5532](https://cloud.githubusercontent.com/assets/17908724/23619912/1fb13af4-028d-11e7-9e4b-c7132f66e4ce.PNG)

Enter code for a second time:
![img_5533](https://cloud.githubusercontent.com/assets/17908724/23619922/2980f63c-028d-11e7-86c7-4ea530bfd41a.PNG)

2nd vote - nothing populated from 1st vote:
![img_5534](https://cloud.githubusercontent.com/assets/17908724/23619945/3be3c3c2-028d-11e7-9b6f-c60e53925135.PNG)

**Comment by heron2014** [comment]
@rickardinho this should be fixed now.

**Comment by rickardinho** [comment]
fixed
