### ISSUE TITLE
Back arrow malfunction when voting

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#231]
After pressing Vote after joining an event and selecting options, the user can quickly press "back" and this results in the malfunction where the screen gets stuck between two screens.  Can we disable back once they have clicked the Vote button, and then make sure the user is redirected to the Feed after voting.  Currently there is a lag sometimes when voting, so perhaps a spinner might be required to let the user know that its loading... and to stop them clicking around.

**Comment by rickardinho** [comment]
![image1](https://cloud.githubusercontent.com/assets/17908724/23517075/20568a6e-ff67-11e6-89f4-ee8e4a8a7ea1.png)

**Comment by heron2014** [comment]
@rickardinho Relates to this comment https://github.com/DRDD2016/native/issues/251#issuecomment-285054520

**Comment by rickardinho** [comment]
fixed
