### ISSUE TITLE
App doesn't load if no WiFi

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#232]
I pulled down from Github and then ran on iPhone.  Wifi was off and 4G signal weak, and app wouldn't go past the "powered by React Native splash screen".  The errors in the screenshot could be seen in Xcode log.

We need some sort of "You are not connected to the Internet, please enable WIFI or 4G and try again" alert, then quit or else load the Feed.

<img width="463" alt="screen shot 2017-03-02 at 19 00 31" src="https://cloud.githubusercontent.com/assets/17908724/23522505/2a2c6478-ff7b-11e6-9d3c-4132557e4180.png">

**Comment by heron2014** [comment]
@rickardinho this should be handled now.

**Comment by rickardinho** [comment]
fixed closing
