### ISSUE TITLE
Individual feed items scroll

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#233]
If i swipe down on a feed item, it scrolls out of view, rather than the whole feed scrolling.  see screenshot

**Comment by heron2014** [comment]
@rickardinho could you please submit the screenshot, so we know exactly what's going on.

**Comment by rickardinho** [comment]
Here it is... i took the screenshot as i've dragged down on the item in the feed (only one item in the feed).  You'll see only half of it is shown as its scrolling down:

![img_5383](https://cloud.githubusercontent.com/assets/17908724/23527384/9ae06630-ff8d-11e6-856e-e79b7f916601.PNG)

**Comment by heron2014** [comment]
@rickardinho this should be fixed now.

**Comment by rickardinho** [comment]
closed
