### ISSUE TITLE
Not navigating from Event Details to Create.

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#234]
After creating a poll I then invite friends using Whatsapp.  I then go back into the event via the feed.  The event details are shown.  I then Click Create, to create a new event, but nothing happens, it stays on the Event details screen.

**Comment by heron2014** [comment]
@rickardinho This should be fixed once the [235](https://github.com/DRDD2016/native/pull/235) is merged.

**Comment by heron2014** [comment]
Reference: 
https://github.com/exponent/ex-navigation#stacknavigation-actions

**Comment by heron2014** [comment]
Refactor:

- ```replace``` the view it kind of work but it wasn't redirecting to the top of the stack on Create because I still had the arrow on the navigation bar

We need to use ```popToTop``` method to go back to the top of the stack

**Comment by heron2014** [comment]
@rickardinho the create screen is accessible after inviting friends. Please have a look.

**Comment by rickardinho** [comment]
yes, seems more stable now.
