### ISSUE TITLE
Host showing as Not Responded on Event screen

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#238]
Host should appear as "Going"
Currently Host is showing as Not Responded.  Host shouldn't be able to change RSVP, should always be Going.

**Comment by rickardinho** [comment]
Or maybe have a label and picture for "Host" instead of the picture at the top left which is currently a placeholder image.

![img_5432](https://cloud.githubusercontent.com/assets/17908724/23526929/cf3145e6-ff8b-11e6-85d0-90c4d25712f4.PNG)

**Comment by heron2014** [comment]
@rickardinho this should be fixed. Host is no longer visible under ```not responded```

**Comment by minaorangina** [comment]
@rickardinho just to clarify, the host was visible by mistake, and should not have been there.  Still have yet to display the host's photo instead of the placeholder, that's coming up soon

**Comment by rickardinho** [comment]
Host no longer visible... so that bit is sorted.  Waiting for hosts photo to be visible before closing.

**Comment by heron2014** [comment]
@rickardinho the host photo should be visible now.

**Comment by rickardinho** [comment]
yes looks okay.
