### ISSUE TITLE
Invitee shouldn't be able to Invite more friends

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#239]
Invitee shouldn't be able to Invite more friends, only the host.
Need to remove the Invite More Friends button for Invitee View.
![img_5432](https://cloud.githubusercontent.com/assets/17908724/23526987/058e6dbc-ff8c-11e6-80b1-3e8b88589f5d.PNG)

**Comment by minaorangina** [comment]
@rickardinho This should be done now

**Comment by rickardinho** [comment]
closed
