### ISSUE TITLE
Where - Places API results not selectable

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#240]
I can now enter non-Places API names (eg. home, or tennis club).  However, if I want to select an API name suggestion, it doesn't select it... it just keeps the characters I typed.  Example... if I type Tennis Club, and then select the suggestion Southwark City Tennis Club, it just puts Tennis Club, instead of the Google place name.

![img_5428](https://cloud.githubusercontent.com/assets/17908724/23527123/8d600aa2-ff8c-11e6-96a5-006a69007374.PNG)

![img_5429](https://cloud.githubusercontent.com/assets/17908724/23527133/98a1cf90-ff8c-11e6-96b2-d431c8ad6156.PNG)

**Comment by heron2014** [comment]
@rickardinho this should be fix now.

**Comment by minaorangina** [comment]
### Notes - accessing component properties from refs
http://stackoverflow.com/questions/24841855/react-js-access-to-component-methods
Example:
```js
class ArticleSearch extends Component {
  render() { return  <div><input type="text" ref="input" /></div> }

  focus() { this.refs.input.focus() }
}

// some other component:

render() { return <div>...<ArticleSearch ref="articleSearch" />...</div> }

doSomething() {
  this.refs.articleSearch.focus()
}
```

**Comment by rickardinho** [comment]
Now I don't get any autocomplete places suggestions...  now and again it flashes up while typing, but as soon as i stop typing it disappears.

![img_5457](https://cloud.githubusercontent.com/assets/17908724/23571458/56296e90-0061-11e7-9299-bda8f3427959.PNG)

**Comment by rickardinho** [comment]
looks to be fixed. closed

**Comment by rickardinho** [comment]
Reopening as the original issue has returned.  If I type a place and don't want to select one of the results, the "Add an option" and "Next" buttons are hidden by the place suggestions, so i can't advance.
![img_5539](https://cloud.githubusercontent.com/assets/17908724/23621493/e239c26c-0292-11e7-9677-c4ba80c284f8.PNG)

**Comment by rickardinho** [comment]
In another example, where no suggestions are provided (which is fine), there is still no next button.

**Comment by rickardinho** [comment]
![img_5556](https://cloud.githubusercontent.com/assets/17908724/23632987/e06078d6-02bb-11e7-9196-ef5f12c025fb.PNG)

**Comment by heron2014** [comment]
@rickardinho As per our conversation over the phone, we have removed the UK restrictions. Please test.

**Comment by rickardinho** [comment]
Not sure this is fixed. see screenshot where Ireland suggestions still hide Next button.  Pressing Return doesn't clear the suggestions dropdown.
![img_5621](https://cloud.githubusercontent.com/assets/17908724/23723609/bd60c296-0441-11e7-80ee-13b00104eccb.PNG)

**Comment by heron2014** [comment]
@rickardinho the dropdown will close when you interact with it.  Did you press Ireland from the suggestions? I just tested on the device, after selection the dropdown is closing.

**Comment by rickardinho** [comment]
Yes but what if I don't want to select any of the suggestions, and go with
my own.. eg " Anita's place".  I can not currently remove the text input
from focus without selecting a suggestion.

Dave

On 9 Mar 2017 3:14 p.m., "Anita" <notifications@github.com> wrote:

@rickardinho <https://github.com/rickardinho> the dropdown will close when
you interact with it. Did you press Ireland from the suggestions? I just
tested on the device, after selection the dropdown is closing.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DRDD2016/native/issues/240#issuecomment-285361889>, or mute
the thread

**Comment by heron2014** [comment]
@rickardinho before, Enter made the keyboard only close. Now Enter makes the keyboard and the dropdown close, as requested. Please test.

**Comment by rickardinho** [comment]
Yes, seems to work okay now. closing
