### ISSUE TITLE
Time inputs should default to blank: TBC

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#242]
As with the web app, time should default to blank, or TBC for display purposes (I think we assumed a default time (eg.00:01) for the calculations though).  Mina might remember.

Also cross buttons to remove time/date inputs aren't appearing.

Related to #201

**Comment by rickardinho** [comment]
![img_5435](https://cloud.githubusercontent.com/assets/17908724/23530825/548995e0-ff9b-11e6-9e85-cc17835b3e4d.PNG)

**Comment by heron2014** [comment]
Remove buttons were added.

**Comment by minaorangina** [comment]
@rickardinho added a toggle switch for when the user wants to leave the time as TBC.  It wasn't possible to manually delete the value inside the input, but the toggle works well.  Please test

**Comment by rickardinho** [comment]
Can we default the TBC toggle to ON?

**Comment by minaorangina** [comment]
@rickardinho ok done.  When you add more options, the time defaults to whatever was in the previous input, which was a feature you requested last time.

**Comment by rickardinho** [comment]
This doesn't seem to work... its still showing a time, eg. TBC is OFF.

**Comment by minaorangina** [comment]
@rickardinho That's strange.  We've tested it on our end and it works as I've described:
<img width="368" alt="screen shot 2017-03-17 at 15 01 24" src="https://cloud.githubusercontent.com/assets/8915092/24049038/b3c192c8-0b22-11e7-9c33-8e3365ada81b.png">
The first input will always be TBC.  If you add subsequent inputs, the time will be whatever was in the previous one, whether TBC or an actual time.

Can you provide screenshots of when this happened?

**Comment by rickardinho** [comment]
I'll retest tonight/tomorrow morning and take some grabs.

**Comment by rickardinho** [comment]
It works now.  I had to delete the app completely from the phone and try again and then it worked.
