### ISSUE TITLE
After creating event and clicking Feed, another event details is shown

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#243]
After creating event and clicking Feed, another event details screen is shown, with the event being the last one viewed through the feed.  Feed button is highlighted, even though event details is shown. - see screenshot.

**Comment by rickardinho** [comment]
![img_5436](https://cloud.githubusercontent.com/assets/17908724/23530789/28cb80f8-ff9b-11e6-992f-0e4f5d9b1d41.PNG)

**Comment by heron2014** [comment]
@rickardinho Relates to this comment https://github.com/DRDD2016/native/issues/251#issuecomment-285054520
