### ISSUE TITLE
JSON Parse error

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#247]
Got this error again.  This time I viewed an event. Deleted it. Went to Feed. Opened another event. Went back to Feed, then Feed was blank.  Waited for Feed to load, nothing loaded so clicked Code and then this.
![img_5438](https://cloud.githubusercontent.com/assets/17908724/23530738/f502d0c8-ff9a-11e6-86c8-4d5935ae9e00.PNG)

**Comment by heron2014** [comment]
@rickardinho this should be fixed now. Please test.

**Comment by rickardinho** [comment]
haven't seen this error recently, closing
