### ISSUE TITLE
Edit Poll only showing first option

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#248]
If I click Edit button on a poll, only the 1st polling option is appearing available to edit.  Shouldn't I be able to edit all options?  see screenshots.  Also the Edit button is very hard to press ( I think the Button is probably too small ).

![img_5439](https://cloud.githubusercontent.com/assets/17908724/23531045/4c2fa028-ff9c-11e6-93d1-a2bb74534b69.PNG)

only Present an award  and 2nd September is showing here:

![img_5440](https://cloud.githubusercontent.com/assets/17908724/23531046/50cf1884-ff9c-11e6-8b4e-71a1b711adf8.PNG)

**Comment by minaorangina** [comment]
@rickardinho The edit button was there by mistake.  Polls can't be editable, as it would mess up the votes etc.  I've removed the button now.

**Comment by rickardinho** [comment]
edit button is hidden - closing
