### ISSUE TITLE
Duplicate events again in feed and calendar

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#249]
At approx 23:10, created a poll and invited friends via Whatsapp.

Then go back to Feed and Calendar and it shows same event twice in Calendar, and 1 poll and 2 created events in Feed... all off the back of one invite (poll).
![img_5442](https://cloud.githubusercontent.com/assets/17908724/23531354/e8dc5adc-ff9d-11e6-81de-fb5dc66faad2.PNG)
![img_5443](https://cloud.githubusercontent.com/assets/17908724/23531358/ed867e0a-ff9d-11e6-9d9a-ea33a1ddf746.PNG)

**Comment by minaorangina** [comment]
@rickardinho I'm going to close issue #218, seeing as it refers to the same thing

**Comment by heron2014** [comment]
@rickardinho Should be fixed now. Please test this.

**Comment by rickardinho** [comment]
fixed
