### ISSUE TITLE
Edit Event not reflected in Event Details.

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#258]
I edited a confirmed event using the Edit button and pressed update.  The date has updated in the Feed for this event (see top event in the Feed in 1st screenshot), However, if I click on the event it shows a different date (the original date) in the Event Details screen (second screenshot).

Also, the event is not showing at all in the Calendar (3rd screenshot).  Possibly because the Calendar is using the original date (which is now in the past).
![img_5452](https://cloud.githubusercontent.com/assets/17908724/23568711/b0b06e1c-0053-11e7-9e49-136c2dc635e2.PNG)
![img_5453](https://cloud.githubusercontent.com/assets/17908724/23568716/b604b63e-0053-11e7-9aa1-679f6f557f27.PNG)
![img_5454](https://cloud.githubusercontent.com/assets/17908724/23568720/ba5b7e84-0053-11e7-91d4-0cd4f1ab18f7.PNG)

**Comment by heron2014** [comment]
@rickardinho this should be fixed now.

**Comment by rickardinho** [comment]
fixed
