### ISSUE TITLE
Calendar seems to very slow to load

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#259]
The spinner is shown for a long time (looks like its hanging and sometimes I give up before it loads because its taking more than 20 seconds).   The Feed doesn't take anywhere near as long, so I suspect its not a network speed issue (as this would affect Calendar and Feed load times).

**Comment by heron2014** [comment]
@rickardinho this should be fixed now. Please test.

**Comment by rickardinho** [comment]
looks to be fixed - closing
