### ISSUE TITLE
Something went wrong when entering an event

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#273]
I got this after pressing Join Event.  

![img_5521](https://cloud.githubusercontent.com/assets/17908724/23611868/ea53f4a8-0270-11e7-92d5-4a7f5d14a422.PNG)

And them I plugged the iPhone in to my laptop and got this:

![img_5522](https://cloud.githubusercontent.com/assets/17908724/23611892/02dd155e-0271-11e7-8159-ee415be9f62b.PNG)

**Comment by rickardinho** [comment]
This has happened again.  this time with code B1vldyo5l.
Also, the screen says try again, but i can't activate the text input, and the button doesn't press, it looks the the screen is locked once this error appears.

**Comment by rickardinho** [comment]
The red error screen actually seems to happen when the phone is rotated, rather than being plugged in.

**Comment by minaorangina** [comment]
@rickardinho this should be fixed now

**Comment by rickardinho** [comment]
looks to be fixed - closed
