### ISSUE TITLE
When details not correct

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#275]
Think we had this bug before but it has reappeared.   I create an event poll with 3 different dates (screenshot 1).

In the confirmed event screen (screenshot 2) it is showing the 3rd of March for all options.

![img_5525](https://cloud.githubusercontent.com/assets/17908724/23613571/e86cf0a2-0277-11e7-992c-a1139b8d58a8.PNG)
![img_5526](https://cloud.githubusercontent.com/assets/17908724/23613580/eddf2924-0277-11e7-976c-2e3acfce7d51.PNG)

**Comment by heron2014** [comment]
@rickardinho this should be working now.

**Comment by rickardinho** [comment]
Looks like its fixed.
