### ISSUE TITLE
Skip button has disappeared from Signup (Profile picture)

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#278]
A few days ago there was a Skip button to skip choosing a profile picture.  This has now disappeared.

**Comment by rickardinho** [comment]
![img_5538](https://cloud.githubusercontent.com/assets/17908724/23620944/b5dde88a-0290-11e7-8019-6a601e9f7b4c.PNG)

**Comment by heron2014** [comment]
@rickardinho very strange. I just tested this screen on simulator and it works as usual: 

<img width="282" alt="screen shot 2017-03-06 at 17 45 33" src="https://cloud.githubusercontent.com/assets/8476884/23622005/dc0cbdac-0294-11e7-8327-e4ce4c36e70a.png">

I have tested on device and I also have the screen as usual.

![img_1159](https://cloud.githubusercontent.com/assets/8476884/23622350/2c5e17d2-0296-11e7-84f2-460b71b3a807.PNG)

Can you please re-test it?

**Comment by rickardinho** [comment]
looks to be fixed now.
