### ISSUE TITLE
Invalid date in event created earlier

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/native#283]
This event used to show a date.  Now it is showing "invalid date" after clicking on the event in the feed.

**Comment by minaorangina** [comment]
@rickardinho do you have a screenshot?  I fixed this within the hour

**Comment by rickardinho** [comment]
![img_5557](https://cloud.githubusercontent.com/assets/17908724/23633259/ec2e03bc-02bc-11e7-99bc-d2748954ae5f.PNG)

I pulled about 30 mins ago.

**Comment by minaorangina** [comment]
fix was done exactly 34 mins ago, according to github.  Try pulling again, will most likely solve it

**Comment by rickardinho** [comment]
fixed - closing
