### ISSUE TITLE
Details component doesn't render Header

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/native#30]
_From @heron2014 on December 14, 2016 16:3_

Currently Header in WHEN SCREEN has nothing in there. Add name, description. 

_Copied from original issue: DRDD2016/sparkn2#40_

**Comment by heron2014** [comment]
This issue is bigger than I thought! I think the whole header components needs to be replaced by Ex-Navigation header (navigation bar) where we can pass data to it as params.

**Comment by heron2014** [comment]
Resolved by #67
