### ISSUE TITLE
Google Places autocomplete

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/native#31]
_From @heron2014 on December 14, 2016 16:47_

Currently we are handling location as text input. Investigate how to implement autocomplete natively.

_Copied from original issue: DRDD2016/sparkn2#41_

**Comment by heron2014** [comment]
To be able to use Google Places we need to sign up for API for ios (and android).

**Comment by heron2014** [comment]
Hi @rickardinho. Could you please signup for Google Places API for ios (and android). 

Here are the links: 

- Sign up for [Google Places API for iOS in Google API Console](https://console.developers.google.com/flows/enableapi?apiid=placesios&reusekey=true) to grab your iOS API key (not browser key).
- Ensure you check out further guides at https://developers.google.com/places/ios-api/start.

(Below steps are optional - the priority is IOS)
- Similarly, sign up for [Google Places API for Android in Google API Console](https://console.developers.google.com/flows/enableapi?apiid=placesandroid&reusekey=true) to grab your Android API key (not browser key).
- Read further API setup guides at https://developers.google.com/places/android-api/signup.



Once this is done and you obtain the both keys - can you please send it to us via email. 

Thanks.

**Comment by heron2014** [comment]
To be able to hide API keys we probably would need to use this module: https://github.com/luggit/react-native-config

**Comment by heron2014** [comment]
Reference to the autocomplete api:
- https://developers.google.com/places/web-service/autocomplete

**Comment by heron2014** [comment]
Update: 
We only need API key from web services as opposed to ios and android. 
- [API key](https://developers.google.com/places/web-service/get-api-key)

**Comment by heron2014** [comment]
Resolved by #87
