### ISSUE TITLE
Redundant button on Profile screen

### ISSUE THREAD

**Issue by heron2014** [DRDD2016/native#69]
Currently we have :

<img width="274" alt="screen shot 2017-01-13 at 14 10 43" src="https://cloud.githubusercontent.com/assets/8476884/21932786/408bb630-d99a-11e6-8641-4b9a915ba092.png">

What is the point to have a button on the Profile screen to ```Return to Main```? There are tabs underneath with the specifics routes with exact the same functionality.

I suggest to remove this button @minaorangina

**Comment by minaorangina** [comment]
@heron2014 Yeah I agree.  I don't know why that button is there, don't think it was in the original web app

**Comment by rickardinho** [comment]
Yes, you can remove this... it was just there to redirect between screens when working on styling, before the new routing was implemented.

**Comment by heron2014** [comment]
Resolved by #71
