### ISSUE TITLE
Replace jsonfileState with redux State

### ISSUE THREAD

**Issue by minaorangina** [DRDD2016/native#8]
_From @rickardinho on December 4, 2016 19:49_

Replace jsonState with real State once Authentication is built (replace references to json file imports in containers with redux state as in original app).

_Copied from original issue: DRDD2016/sparkn2#5_

**Comment by minaorangina** [comment]
JSON is causing problems with emulating the app on Xcode and iPhone device.  Will need replacing asap.  Job for @heron2014 and myself

**Comment by heron2014** [comment]
json files has been replaces by redux.
