### ISSUE TITLE
Error running Jest on CircleCI: “npm test died unexpectedly”

### ISSUE THREAD

**Issue by heron2014** [DRDD2016/native#96]
Running my Jest test suite on CircleCI is much slower compared to locally, resulting in an error in CircleCI saying npm test died unexpectedly.

Same issue on stackoverflow: http://stackoverflow.com/questions/36747251/error-running-jest-on-circleci-npm-test-died-unexpectedly

**Comment by heron2014** [comment]
Related issue: https://github.com/facebook/jest/issues/2346

**Comment by minaorangina** [comment]
Ended up passing a `----runInBand` flag to jest, as suggested in the jest issue above
